---
- name: Trust RVM's developer GPG key
  command: gpg --keyserver hkp://keys.gnupg.net --recv-keys 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
- name: Install RVM on single user mode
  shell: curl -sSL https://get.rvm.io | bash -sl stable
- name: Set rvmrc
  copy: src=.rvmrc dest=~/.rvmrc
