---
- name: Check RVM installed
  shell: /usr/bin/bash -lc "rvm"
  register: rvm_installed
  ignore_errors: True
  changed_when: False
  check_mode: no
- name: Install RVM
  include_tasks: install.yml
  when: rvm_installed is failed
- name: Update RVM
  include_tasks: update.yml
  when: rvm_installed is succeeded
