---
- hosts: burn-e
  remote_user: ubuntu
  become: yes
  tasks:
    - name: Upgrade all packages to the last version
      apt:
        name: "*"
        state: latest
        update_cache: yes
        cache_valid_time: 3600
    - name: Configure static IP
      copy:
        dest: /etc/netplan/01-netcfg.yaml
        content: |
          network:
            version: 2
            renderer: networkd
            ethernets:
              eth0:
                dhcp4: no
                dhcp6: no
                addresses: [192.168.0.5/24]
                gateway4: 192.168.0.1
                nameservers:
                  addresses: [1.1.1.1,1.0.0.1]
      register: network_conf
    - name: Apply network changes
      shell: netplan apply
