---
- hosts: local
  connection: local
  vars:
    notebook:
      ps_ac_string: 'ACAD'
      ps_bt_string: 'BAT1'
    nvidia_legacy: true
  environment:
    PATH: "/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl"
  roles:
    - xorg # Required by font configuration part of common
    - ssh # Required by common (openssh)
    - common
    - intel-ucode
    - intel-graphics
    - nvidia
    - awesomewm
    - lightdm
    - acpid
    - laptop-mode-tools
    - ufw
    - zsh
    - neovim
    - workspace
    - temperature
    - gaming
    - grub
