---
- hosts: local
  connection: local
  vars:
    GRUB_CMDLINE_LINUX_DEFAULT: "loglevel=3 quiet iommu=soft"
  environment:
    PATH: "/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl"
  roles:
    - xorg
    - ssh
    - common
    - nvidia
    - awesomewm
    - lightdm
    - acpid
    - ufw
    - zsh
    - neovim
    - workspace
    - temperature
    - gaming
    - grub
