---
- name: Get workspace main repository
  git: repo=git@gitlab.com:rafamanzo/workspace.git dest=~/workspace accept_hostkey=yes update=no
- name: Setup RVM
  include_tasks: rvm/main.yml
- name: Install PostgreSQL
  include_tasks: postgresql.yml
- name: Install PhantomJS package
  yay: name=phantomjs-bin state=present force=yes
  become: yes
  become_user: super{{ ansible_env.LOGNAME }}
  become_method: sudo
- name: Install libmariadbclient
  pacman: name=libmariadbclient state=present force=yes
  become: yes
  become_user: root
  become_method: sudo
- name: Install C++ development tools
  include_tasks: cpp.yml
- name: Install MSc dependencies
  include_tasks: msc_dependencies.yml
- name: Install LaTeX
  include_tasks: latex.yml
- name: Install Python Virtualenv
  include_tasks: python-virtualenv/main.yml
- name: Install FDM dependencies
  include_tasks: fdm_dependencies.yml
- name: Install sshpass
  pacman: name=sshpass state=present
  become: yes
  become_user: root
  become_method: sudo
- name: Install docker
  pacman: name=docker state=present
  become: yes
  become_user: root
  become_method: sudo
- name: Install vagrant
  pacman: name=vagrant state=present
  become: yes
  become_user: root
  become_method: sudo
- name: Install sshfs
  pacman: name=sshfs state=present
  become: yes
  become_user: root
  become_method: sudo
- name: Install sshuttle
  pacman: name=sshuttle state=present
  become: yes
  become_user: root
  become_method: sudo
- name: Install screen
  pacman: name=screen state=present
  become: yes
  become_user: root
  become_method: sudo
- name: Install smartbot dependencies
  include_tasks: smartbot_dependencies.yml
- name: Install mandae dependencies
  include_tasks: mandae_dependencies.yml
- name: Install chromium
  pacman: name=chromium state=present
  become: yes
  become_user: root
  become_method: sudo
