---
- name: Get workspace main repository
  git: repo=git@gitlab.com:rafamanzo/workspace.git dest=~/workspace accept_hostkey=yes update=no
- name: Setup RVM
  include_tasks: rvm/main.yml
- name: Install PostgreSQL
  include_tasks: postgresql.yml
- name: Install libmariadbclient
  pacman: name=libmariadbclient state=present force=yes
  become: yes
  become_user: root
  become_method: sudo
- name: Install base-devel package
  pacman: name=base-devel state=present force=yes
  become: yes
  become_user: root
  become_method: sudo
- name: Install LaTeX
  include_tasks: latex.yml
- name: Install Python Virtualenv
  include_tasks: python-virtualenv/main.yml
- name: Install FDM dependencies
  include_tasks: fdm_dependencies.yml
- name: Install sshpass
  pacman: name=sshpass state=present
  become: yes
  become_user: root
  become_method: sudo
- name: Install docker
  pacman: name=docker state=present
  become: yes
  become_user: root
  become_method: sudo
- name: Add user to docker group
  user: name={{ ansible_env.LOGNAME }} append=yes groups=docker
  become: yes
  become_user: root
  become_method: sudo
- name: Install vagrant
  pacman: name=vagrant state=present
  become: yes
  become_user: root
  become_method: sudo
- name: Install sshfs
  pacman: name=sshfs state=present
  become: yes
  become_user: root
  become_method: sudo
- name: Install sshuttle
  pacman: name=sshuttle state=present
  become: yes
  become_user: root
  become_method: sudo
- name: Install screen
  pacman: name=screen state=present
  become: yes
  become_user: root
  become_method: sudo
- name: Install redis
  pacman: name=redis state=present force=yes
  become: yes
  become_user: root
  become_method: sudo
- name: Install mongodb
  yay: name=mongodb-bin state=present
  become: yes
  become_user: super{{ ansible_env.LOGNAME }}
  become_method: sudo
- name: Install yarn
  pacman: name=yarn state=present
  become: yes
  become_user: root
  become_method: sudo
- name: Install chromium
  pacman: name=chromium state=present
  become: yes
  become_user: root
  become_method: sudo
- name: Install ag
  pacman: name=the_silver_searcher state=present
  become: yes
  become_user: root
  become_method: sudo
- name: Install gedit
  pacman: name=gedit state=present
  become: yes
  become_user: root
  become_method: sudo
- name: Install tk
  pacman: name=tk state=present
  become: yes
  become_user: root
  become_method: sudo
- name: Install kdiff3
  pacman: name=kdiff3 state=present
  become: yes
  become_user: root
  become_method: sudo
- name: Install zoom
  yay: name=zoom state=present
  become: yes
  become_user: super{{ ansible_env.LOGNAME }}
  become_method: sudo
- name: Install cmake
  yay: name=cmake state=present
  become: yes
  become_user: root
  become_method: sudo
- name: Install wkhtmltopdf
  yay: name=wkhtmltopdf state=present
  become: yes
  become_user: root
  become_method: sudo
- name: Install MariaDB
  yay: name=mariadb state=present
  become: yes
  become_user: root
  become_method: sudo
- name: Init MariaDB
  shell: mariadb-install-db --user=mysql --basedir=/usr --datadir=/var/lib/mysql
  args:
    creates: /var/lib/mysql
  become: yes
  become_user: root
  become_method: sudo
- name: Install man-db package
  pacman: name=man-db state=present
  become: yes
  become_user: root
  become_method: sudo
- name: Install man-pages package
  pacman: name=man-db state=present
  become: yes
  become_user: root
  become_method: sudo
