---
- name: Install nvidia GPU driver package
  pacman: name=nvidia state=present
  become: yes
  become_user: root
  become_method: sudo
  when: not nvidia_legacy
- name: Install legacy nvidia GPU driver package
  yay: name=nvidia-390xx-dkms state=present
  become: yes
  become_user: super{{ ansible_env.LOGNAME }}
  become_method: sudo
  when: nvidia_legacy
- name: Install nvidia GPU driver 32 bits lib package
  pacman: name=lib32-nvidia-utils state=present
  become: yes
  become_user: root
  become_method: sudo
- block:
  - name: Install Bumblebee packages
    pacman: name={{ item }} state=present
    with_items:
      - bumblebee
      - lib32-virtualgl
      - primus
      - lib32-primus
  - name: Setup Bumblebee systemd unit
    systemd: name=bumblebeed state=started enabled=yes
  - name: Allow current user to use Bumbleblee
    user:
      name: '{{ ansible_env.LOGNAME }}'
      groups: bumblebee
      append: yes
  become: yes
  become_user: root
  become_method: sudo
  when: notebook is defined
