---
- name: Install grml-zsh-config package
  pacman: name=grml-zsh-config state=present
  become: yes
  become_user: root
  become_method: sudo
- name: Install zsh-syntax-highlighting package
  pacman: name=zsh-syntax-highlighting state=present
  become: yes
  become_user: root
  become_method: sudo
- name: Install zsh-autosuggestions package
  yay: name=zsh-autosuggestions state=present
  become: yes
  become_user: super{{ ansible_env.LOGNAME }}
  become_method: sudo
- name: Install python-virtualenvwrapper package
  yay: name=python-virtualenvwrapper state=present
  become: yes
  become_user: super{{ ansible_env.LOGNAME }}
  become_method: sudo
- name: Install nvm package
  yay: name=nvm state=present
  become: yes
  become_user: super{{ ansible_env.LOGNAME }}
  become_method: sudo
- name: Create zshrc
  copy: src=.zshrc dest={{ ansible_env.HOME }}/.zshrc
- name: Set zsh as default shell
  user: name={{ ansible_env.LOGNAME }} shell=/usr/bin/zsh
  become: yes
  become_user: root
  become_method: sudo
