---
- name: Install lm_sensors package
  pacman: name=lm_sensors state=present
  become: yes
  become_user: root
  become_method: sudo
- name: Configure lm_sensors (detect the chips)
  command: sensors-detect --auto
  args:
    creates: /etc/conf.d/lm_sensors
  become: yes
  become_user: root
  become_method: sudo
- name: Install psensor
  yay: name=psensor state=present
  become: yes
  become_user: super{{ ansible_env.LOGNAME }}
  become_method: sudo
