- name: Install git package
  pacman: name=git state=present
  become: yes
  become_user: root
  become_method: sudo
- name: Set git user name
  git_config:
    name: user.name
    scope: global
    value: "{{ git.name }}"
- name: Set git user email
  git_config:
    name: user.email
    scope: global
    value: "{{ git.email }}"
- name: Set git pull behaviour for divergent branches
  git_config:
    name: pull.ff
    scope: global
    value: only
