---
- name: Setup CPU scaling
  include_tasks: cpu_scaling.yml
  become: yes
  become_user: root
  become_method: sudo
- name: Install laptop-mode-tools-git
  # Git version preferred over the mainstream beacuse of sustemd incompatibility:
  # * https://bbs.archlinux.org/viewtopic.php?id=209100
  pacaur: name=laptop-mode-tools-git state=present
  become: yes
  become_user: super{{ ansible_env.LOGNAME }}
  become_method: sudo
- name: Configure Laptop Mode Tools
  include_tasks: configure.yml
  become: yes
  become_user: root
  become_method: sudo
- name: Enable laptop-mode
  service: name=laptop-mode enabled=yes
  become: yes
  become_user: root
  become_method: sudo
- name: Start laptop-mode
  service: name=laptop-mode state=started
  become: yes
  become_user: root
  become_method: sudo
