---
- name: Set GRUB_CMDLINE_LINUX_DEFAULT
  replace:
    path: /etc/default/grub
    regexp: 'GRUB_CMDLINE_LINUX_DEFAULT=.*'
    replace: "GRUB_CMDLINE_LINUX_DEFAULT=\"{{ GRUB_CMDLINE_LINUX_DEFAULT }}\""
  when: GRUB_CMDLINE_LINUX_DEFAULT is defined
  register: set_GRUB_CMDLINE_LINUX_DEFAULT
  become: yes
  become_user: root
  become_method: sudo
- name: Generate GRUB config
  command: grub-mkconfig -o /boot/grub/grub.cfg
  when: set_GRUB_CMDLINE_LINUX_DEFAULT is changed
  become: yes
  become_user: root
  become_method: sudo
